package com.yonyou.itf.mdm07.sharing;

import com.ufida.eip.service.Level;
import com.ufida.eip.service.annotation.Operation;
import com.ufida.eip.service.annotation.Parameter;
import com.ufida.eip.service.annotation.Service;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.0
 * 2014-10-28T15:18:30.527+08:00
 * Generated source version: 2.7.0
 * 
 */
@WebService(targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", name = "IMdSharingThirdPartServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.ObjectFactory.class})
@Service(version = "1.0.0", description = "", level = Level.PLATFORM)
public interface IMdSharingThirdPartServicePortType {

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
    @Action(input = "urn:loadMd", output = "urn:loadMdResponse")
    @RequestWrapper(localName = "loadMd", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.LoadMd")
    @WebMethod(action = "urn:loadMd")
    @ResponseWrapper(localName = "loadMdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.LoadMdResponse")
    @Operation(description = "")
    public com.yonyou.itf.mdm07.sharing.OuterSystemRetVO loadMd(
        @WebParam(name = "string0", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.String string0
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
    @Action(input = "urn:distributeMd", output = "urn:distributeMdResponse")
    @RequestWrapper(localName = "distributeMd", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.DistributeMd")
    @WebMethod(action = "urn:distributeMd")
    @ResponseWrapper(localName = "distributeMdResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.DistributeMdResponse")
    @Operation(description = "")
    public com.yonyou.itf.mdm07.sharing.OuterSystemRetVO distributeMd(
        @WebParam(name = "string0", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.String string0,
        @WebParam(name = "string1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.String string1,
        @WebParam(name = "string2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.String string2
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
    @Action(input = "urn:loadMdBatch", output = "urn:loadMdBatchResponse")
    @RequestWrapper(localName = "loadMdBatch", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.LoadMdBatch")
    @Operation(description = "")
    @WebMethod(action = "urn:loadMdBatch")
    @ResponseWrapper(localName = "loadMdBatchResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.LoadMdBatchResponse")
    public com.yonyou.itf.mdm07.sharing.OuterSystemRetVO loadMdBatch(
        @WebParam(name = "string0", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.String string0,
        @WebParam(name = "int1", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.Integer int1,
        @WebParam(name = "int2", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.Integer int2
    );

    @WebResult(name = "return", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
    @Action(input = "urn:getRemoteMdCount", output = "urn:getRemoteMdCountResponse")
    @RequestWrapper(localName = "getRemoteMdCount", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.GetRemoteMdCount")
    @Operation(description = "")
    @WebMethod(action = "urn:getRemoteMdCount")
    @ResponseWrapper(localName = "getRemoteMdCountResponse", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService", className = "com.yonyou.itf.mdm07.sharing.imdsharingthirdpartservice.GetRemoteMdCountResponse")
    public com.yonyou.itf.mdm07.sharing.OuterSystemRetVO getRemoteMdCount(
        @WebParam(name = "string0", targetNamespace = "http://sharing.mdm07.itf.yonyou.com/IMdSharingThirdPartService")
        java.lang.String string0
    );
}
